name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}


    - name: Copy env file
      run: cp .env.example .env

    - name: Set OpenAI API key
      run: |
        echo "OPENAI_API_KEY=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" > .env

    - name: Run install
      run: npm install  
    - name: Run dev  
      run: npm run dev

